[package]
name = "advent-of-code-2019"
version = "1.0.0"
authors = ["Marc Jamot <marcjamot@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"

[dev-dependencies]
quickcheck = "0.9.0"
quickcheck_macros = "0.8.0"
